### ISSUE TITLE
Possible incorrect use of floor function

### ISSUE THREAD

**Issue by snigo** [siege-media/contrast-ratio#35]
Display contrast values seems to have incorrect rounding.

To recreate:
Precise contrast between `white` and `hsl(294, 85%, 39%)`: 6.169999638792364
Display value: 6.16

Seems strange to me, is there any particular reason you use `floor` instead of `round`?

**Comment by LeaVerou** [comment]
See this discussion on why the change to floor was implemented: https://github.com/LeaVerou/contrast-ratio/issues/13

**Comment by snigo** [comment]
Compliance and numerical representation sound like different concerns, you can still show correct rounding and correct compliance at the same time:
![Screenshot 2020-04-11 at 10 59 04](https://user-images.githubusercontent.com/56631054/79039719-8bb66300-7be3-11ea-8cc3-709180621693.png)

But I totally get it, feel free to close :)

**Comment by LeaVerou** [comment]
Agreed, but given the use cases, flooring seemed like a better decision. Usability > maths (and I say this as a math-loving person :)
