### ISSUE TITLE
Increments with opacity is not working optimally.

### ISSUE THREAD

**Issue by ollie-iterators** [siege-media/contrast-ratio#48]
I think that the code would be improved if you were able to change the value of the opacity for colors in increments of 0.01 instead of changing it by values of 1, like for the other values. This is because opacity only has a range of 0 to 1, and would mean that decreasing opacity with the down button would only work if opacity was set to 1, and vice versa.

**Comment by SethFalco** [comment]
This probably belongs in [LeaVerou/incrementable](https://github.com/LeaVerou/incrementable).

**Comment by ollie-iterators** [comment]
Moved to LeaVerou/incrementable
