### ISSUE TITLE
Color Picker to choose color 

### ISSUE THREAD

**Issue by mohammedzamakhan** [siege-media/contrast-ratio#5]
It would be cooler if you put color picker directly in the project, so that people do not have to go and pick color from else where

**Comment by bboyle** [comment]
:+1: (but it's an awesome tool even without that)

**Comment by SethFalco** [comment]
Old issue, but figured I'd just comment.

I feel the current UI looks pretty sexy, but I do think it'd be nicer if it used an actual color picker.
I can't speak for all operating systems and browsers, but with Firefox on Ubuntu it does still allow using standard web colors as well by name, and whatever color code format.

```html
<input type="color"/>
```

Is all it'd take, and we'll have a native color picker to use which the user will most likely already be familiar with.  

![Peek 2020-11-01 23-10](https://user-images.githubusercontent.com/22801583/97816732-6c724680-1c97-11eb-8861-20ab95a76fe6.gif)
> Result isn't perfect since it's not clear the colors can be clicked, would want a better option than that. :thinking: But you get my point.

**Comment by LeaVerou** [comment]
The whole point of contrast-ratio is that it allows any CSS color, regardless of how it's specified. `<input type=color>` only allows hex colors. There are plenty of other contrast checkers that use color pickers and only allow for hex colors. That said, I wouldn't be opposed to a PR that adds a color picker as a discreet alternative, but not one that *replaces* the current free form input.
