### ISSUE TITLE
Come up with mobile friendly design for the site

### ISSUE THREAD

**Issue by SethFalco** [siege-media/contrast-ratio#53]
The website isn't very friendly to use on mobile.

If I can find time later for it, I'll see if this is something I can handle and revamp the site for mobile without impacting the desktop usage.

**Comment by mnosov622** [comment]
Hello @SethFalco !

I would love to work on this issue. Could you assign it to me, please ?

**Comment by SethFalco** [comment]
I actually _can't_ assign it to you, I'm not a maintainer.
However, you don't need to be assigned a task to work on it!

I was planning to ask a friend of mine if they had time to come up with mobile designs, but if you're capable of designing things yourself, feel free.
