### ISSUE TITLE
Lightness values of 1 in HSLA are reported as semi-transparent when colons are present

### ISSUE THREAD

**Issue by kevinSuttle** [siege-media/contrast-ratio#6]
For example 
`hsla(0, 100%, 100%, 1);` breaks lightness interpretation,
![screenshot 2014-03-24 10 27 26](https://f.cloud.github.com/assets/95672/2501088/d6c98ab0-b368-11e3-89b4-b9098c4aeee3.png)

...but removing the semi-colons fixes it.
![screenshot 2014-03-24 10 28 43](https://f.cloud.github.com/assets/95672/2501114/06e2cf90-b369-11e3-9972-8da7b6edea9a.png)

**Comment by LeaVerou** [comment]
The semicolons make the color invalid, so it's dropped and you see the contrast ratio of whatever was there before (which is desired behavior in cases when you're manually typing the color and you don't want the UI to keep flickering every time your intermediate keystrokes result in an invalid color).

**Comment by mathewballard** [comment]
@kevinSuttle What tool are you using to test the contrast?
