### ISSUE TITLE
gulp Plugin

### ISSUE THREAD

**Issue by lukasoppermann** [siege-media/contrast-ratio#9]
Hey @leaVerou I would really apprechiate this color ratio as a gulp Plugin, so it can be integrated into a typical workflow. 

I guess many others would as well, since it addresses an important issue.

Any chance of you turning it into a gulp plugin?

Cheers,
Lukas

**Comment by LeaVerou** [comment]
Probably not, I really don’t have the time, sorry. But you’re welcome to! Then perhaps you could send a PR too :)

**Comment by lukasoppermann** [comment]
Hmm, that is sad. :( Sadly I would really not know how to do it, so I can not send a PR.

**Comment by yairEO** [comment]
@lukasoppermann  - I don't understand your need. 

>  ...can be integrated into a typical workflow

what exactly do you mean by "typical workflow"?

I would tell you **my** typical workflow: 
find out if this tool is on NPM (not, but should) and import it so i could use this on the client-side.

Gulp, on the other hand, is not for browsers, and is just a build-process tool, so I highly doubt you actually need this script for Gulp. There's nothing color-related going on in your gulpfile probably.

**Comment by lukasoppermann** [comment]
Hey @yairEO, the idea was to have it in gulp, so you could drop it in and it would check your page for elements where the bg and font color ratio does not fulfill the requirements. Basically like a kind of linting.

However, I am currently not in need of this, so if you ask me, this issue can be closed.
